#release configuration
#Thu Feb 19 10:46:30 CET 2026
completedPhase=scm-commit-release
exec.additionalArguments=-DskipTests -Dmaven.javadoc.skip\=true
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.com.mycompany.app\:my-app=1.0.1-SNAPSHOT
project.rel.com.mycompany.app\:my-app=1.0.0
project.scm.com.mycompany.app\:my-app.tag=my-app-1.0.0
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=true
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.id=git
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=my-app-1.0.0
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:git.com/my-app
